FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app
COPY mvnw .
COPY .mvn .mvn

COPY pom.xml .
COPY src ./src

# Make mvnw executable
RUN chmod +x mvnw

# Build the app
RUN ./mvnw clean package -DskipTests

# Expose port (Spring Boot default)
EXPOSE 8080

# Run the app
CMD ["java", "-jar", "target/chatbot-0.0.1-SNAPSHOT.war"]
